# Generated by Django 5.2.16 on 2026-07-27 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Data Analyst', 'Data Analyst'), ('Software Engineer', 'Software Engineer'), ('Django Developer', 'Django Developer'), ('SQL Developer', 'SQL Developer')], max_length=100)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('1-2 Years', '1-2 Years'), ('3-5 Years', '3-5 Years')], max_length=50)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Completed', 'Completed')], default='Started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('AI', 'AI'), ('USER', 'USER')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interview.interviewsession')),
            ],
        ),
    ]
