# Generated by Django 5.2.16 on 2026-07-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
