# Generated by Django 5.2.16 on 2026-07-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewsession_question_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='interviewreport',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interview.interviewsession'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='question_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
