# Generated by Django 5.2.16 on 2026-07-31 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interview.conversation')),
            ],
        ),
    ]
